---
author: LISA
banner: img/banners/blog-2.png
categories:
- componentes
date: "2021-10-02T11:50:46+02:00"
description:
tags:
- componentes
- ciencia abierta
title: Introducción
---
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">


```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, cache = FALSE,echo = F)
pacman::p_load(dplyr, kableExtra,sjlabelled, readxl)
options(scipen=999,
        knitr.kable.NA = '',
        knitr.graphics.error = FALSE)
Sys.setlocale("LC_ALL", "ES_ES.UTF-8")
```
<style>
.disegno{color: lightblue;}
.datos{color: lightgreen;}
.repro{color: pink;}
.publibres{color: orange;}
</style>

# Componentes

<div style="float: right;">

| <i class="ai ai-preregistered ai-9x" style="color:lightblue; "></i> | <i class="ai ai-open-data ai-9x" style="color:lightgreen;;"></i>      |
|----------------------------------------------------------------------------------|-----------------------------------------------------------------------------------|
| <i class="ai ai-open-materials ai-9x" style="color:pink;"></i>      | <i class="ai ai-open-access-square ai-9x" style="color:orange;"></i> |

</div>

Una de los objetivos [**Laboratorio de Investigación Social Abierta** ]() es generar una propuesta de trabajo siguiendo los principios y prácticas de la ciencia abierta. Esta propuesta se constituye a través de la elaboración de **herramientas** conceptuales y prácticas en cuatro componentes: <span class="disegno">(1) diseño transparente, </span>  <span class="datos"> (2) apertura de datos,  </span> <span class="repro"> (3) análisis reproducibles </span> y <span class="publibres"> (4) publicaciones libres </span>. Estos componentes representan cómo los cientistas sociales podemos contribuir con la apertura del proceso de investigación en sus distintos momentos.

En el ámbito de las ciencias sociales, los esfuerzos por incrementar la apertura de los procesos de investigación han sido **escasos** y ha estado su presencia ha sido  predominante en las comunidades científicas de **habla inglesa**.

Por este motivo, LISA se propone contribuir a la comunidad de ciencias sociales de habla hispana a través serie de herramientas que contribuyan a incrementar la apertura de las investigaciones científicas.

En el siguiente video se resume nuestra propuesta:
