---
author: LISA
categories:
- componentes
date: "2021-12-28T10:50:46+02:00"
description: Talleres
keywords:
- codebook
- datos
- abierto
title: "Taller Introducción a la Ciencia Abierta"
linkcolor: blue
link-citations: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, cache = FALSE,echo = F)
pacman::p_load(dplyr, kableExtra,sjlabelled, readxl)
options(scipen=999,
        knitr.kable.NA = '',
        knitr.graphics.error = FALSE)
Sys.setlocale("LC_ALL", "ES_ES.UTF-8")
```


# Taller Introducción a la Ciencia Abierta:
## Pre-registros y Pre-prints

Actualmente la ciencia vive una crisis de apertura, que se ha asociado principalmente a las barreras para acceder a los productos finales de la investigación (artículos), así como también a la transparencia general de los diseños de investigación, levantamiento de datos y análisis de la información. El presente taller entrega una breve introducción general a los orígenes, características y consecuencias del cierre científico, para luego enfocarse en dos herramientas prácticas para la apertura: los pre-registros y los pre-prints. Los pre-registros permiten abrir los diseños de investigación en plataformas públicas, comprometiendo hipótesis de investigación antes del análisis y levantamiento de los datos, mientras los pre-prints facilitan el acceso abierto y oportuno a los productos de investigación previo a su publicación en revistas académicas.

Este taller está organizado por el Laboratorio de Ciencia Social Abierta (LISA), iniciativa de COES que busca generar información y orientaciones para la apertura de la investigación cientifica en ciencias sociales.

El taller se realizará de manera híbrida. Contamos con 20 cupos presenciales y 20 online previa inscripción en [este formulario](link). 

