* Encoding: UTF-8.

CODEBOOK  Duration__in_seconds_ [s] educat [n] sexo [n] edad [n] get_ah_1 [n] sal_perc_1 [s]
/VARINFO POSITION LABEL TYPE FORMAT MEASURE ROLE VALUELABELS MISSING ATTRIBUTES
/OPTIONS VARORDER=VARLIST SORT=ASCENDING MAXCATS=200
/STATISTICS COUNT PERCENT MEAN STDDEV QUARTILES.